#!/bin/bash

set -ex

COMPOSE_FILE=$BUILDKITE_PLUGIN_RUN_DOCKER_COMPOSE_COMPOSE_FILE

docker-compose -f $COMPOSE_FILE logs --tail="all"

# Try to spin down services
docker-compose -f $COMPOSE_FILE kill || true
docker-compose -f $COMPOSE_FILE down || true
