#!/bin/bash

set -ex

COMPOSE_FILE=$BUILDKITE_PLUGIN_RUN_DOCKER_COMPOSE_COMPOSE_FILE

if [ "$BUILDKITE_PLUGIN_RUN_DOCKER_COMPOSE_LOGS" == "true" ]; then
  echo "~~~ :docker: docker-control service logs" >&2

  docker-compose -f $COMPOSE_FILE logs --tail="all"
fi

# Try to spin down services
echo "~~~ :docker: docker-control cleanup" >&2
docker-compose -f $COMPOSE_FILE kill || true
docker-compose -f $COMPOSE_FILE down || true
